apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: github-etl
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  DATABASE_USER: {{ .Values.database.user | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.database.password | b64enc | quote }}
