{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-postgres
  namespace: github-etl
  labels:
    app: {{ .Chart.Name }}-postgres
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 5432
    targetPort: postgres
    protocol: TCP
    name: postgres
  selector:
    app: {{ .Chart.Name }}-postgres
{{- end }}