replicaCount: 1

image:
  repository: ghcr.io/ejpolicarpio/github-etl
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  APP_NAME: github-etl
  LOG_LEVEL: INFO
  DATABASE_HOST: github-etl-postgres
  DATABASE_PORT: "5432"
  DATABASE_NAME: github_etl

database:
  user: postgres
  password: postgres

postgresql:
  enabled: true
  image: postgres:15
  storage:
    size: 1Gi
    class: standard
  resources:
    limits:
      cpu: 500m
      memory: 512mi
  requests:
    cpu: 250m
    memory: 256mi