replicaCount: 1

image:
  repository: ghcr.io/ejpolicarpio/github-etl
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

database:
  user: postgres
  password: postgres

postgresql:
  enabled: true
  image: postgres:15
  storage:
    size: 1Gi
    class: standard
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
  requests:
    cpu: 250m
    memory: 256mi