apiVersion: v2
name: observability
description: Grafana observability stack with Prometheus, Loki, Tempo, and Alloy
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  # Prometheus + Grafana + Alertmanager (complete monitoring stack)
  - name: kube-prometheus-stack
    version: 57.0.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled

  # Loki for log aggregation
  - name: loki
    version: 5.47.0
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled

  # Tempo for distributed tracing
  - name: tempo
    version: 1.7.0
    repository: https://grafana.github.io/helm-charts
    condition: tempo.enabled

  # Alloy for telemetry collection
  - name: alloy
    version: 0.3.0
    repository: https://grafana.github.io/helm-charts
    condition: alloy.enabled

  # OpenTelemetry Operator for auto-instrumentation
  - name: opentelemetry-operator
    version: 0.53.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry.enabled